// document.write("This is external File<br/>");
// document.write("Paragraph 1 <br/>");
// document.write("Paragraph 2");
// n1 = "Mahim";
// w="wedds"
// n2 = "Priya";
// document.write(n1+ " "+w+" " + n2 + "<br/>");
// var name = "Sayeed Ibne Saif";
// var age = 22;
// var point = 3.60;
// var num1 = 30;
// var num2 = 60;
// var add = num1+num2;
// var sub = num2 - num1;
// var mul = num1*num2;
// var div = num2/num1;
// document.write(name+" is "+typeof(name) + "<br/>");
// document.write(age+" is "+typeof(age)+ "<br/>");
// document.write(point+" is "+typeof(point)+ "<br/>");
// document.write(num1 + " + " + num2+ " = " + add+ "<br/>");
// document.write(num2 + " - " + num1+ " = " + sub+ "<br/>");
// document.write(num1 + " * " + num2+ " = " + mul+ "<br/>");
// document.write(num2 + " / " + num1+ " = " + div+ "<br/>");

document.write("Temparature converter - <br/>");
// var far = prompt("Enter farenheit- ");
// var cel = prompt("Enter celsius- ");
var far = 100;
var cel = 40;
var structC = ((far-32)*5)/9;
var structF = (((cel*9)/5)+32);
document.write(far +" in celsius is- " + structC.toFixed(2) +"<br/>");
document.write(cel +" in farenheit is- " + structF +"<br/>");
document.write("AREA OF CIRCLE - <br/>");
var radius = 4;
var pi = 3.1416;
var areaC = 2*pi*radius;
document.write("If radius is "+ radius + " the area is- " + areaC);
document.write("<br/>AREA OF RACTANGULAR - <br/>");
var length = 5;
var breadth = 10;
var areaR = length*breadth;
document.write("If length is "+ length + " and breadth is "+ breadth +" the area is- " + areaR);
document.write("<br/>AREA OF TRI-ANGLE - <br/>");
var height = 10;
var land  = 5;
var areaT = (0.5*height*land);
document.write("If height is "+ height + " and land is "+ land +" the area is- " + areaT);
